"""``palace refresh`` — explicit, cache-first metadata/impact updates.

The only network entry in the shared core: live transport exists solely
behind ``--live`` (explicit network authorization). Without ``--live`` every lookup is
served from the Bibliographic Cache and a miss is reported, not fetched.
Outputs land ONLY in Derived State (``<state_dir>/impact/``) and as proposal
reports — this tool never edits a Vault card; card updates go through the
orchestrator's packaged confirmation, and weight edits additionally through
the weight-migration gate. ``govern`` never calls this module.
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from ..graph.identity import extract_external_ids, parse_frontmatter, split_frontmatter
from .cache import BibliographicCache, RateLimiter
from .impact import build_snapshot, classify_all
from .providers import ADAPTERS, ProviderError, live_transport

IMPACT_DIRNAME = "impact"
SNAPSHOTS_NAME = "snapshots.json"
DRYRUN_NAME = "weight-dryrun.md"
CITATIONS_NAME = "citations-proposal.md"

CARD_FIELDS = ("slug", "source", "journal_if", "citations", "citations_date", "year", "domain", "weight")


def read_card_fields(path):
    text = path.read_text(encoding="utf-8")
    fm_lines, _, _ = split_frontmatter(text, origin=path.name)
    fields, _ = parse_frontmatter(fm_lines, origin=path.name)
    return {key: fields.get(key) for key in CARD_FIELDS}


def scope_cards(vault, scope):
    papers = sorted(
        p for p in (Path(vault) / "papers").glob("*.md") if p.name != "INDEX.md"
    )
    if scope == "all":
        return papers
    if scope.startswith("domain:"):
        slug = scope.split(":", 1)[1]
        selected = []
        for path in papers:
            domains = read_card_fields(path).get("domain") or []
            if slug in domains:
                selected.append(path)
        return selected
    return [p for p in papers if p.stem == scope]


def _snapshot_path(state):
    return Path(state) / IMPACT_DIRNAME / SNAPSHOTS_NAME


def load_snapshots(state):
    path = _snapshot_path(state)
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_snapshots(state, snapshots):
    path = _snapshot_path(state)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(snapshots, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return path


def read_jcr_snapshot(path):
    """User-supplied licensed JCR export as JSON: {venue: {category: quartile}}."""
    if path is None:
        return {}
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return {str(venue).lower(): quartiles for venue, quartiles in data.items()}


def refresh_snapshots(vault, state, scope="all", live=False, jcr=None, mailto=None):
    """Resolve each in-scope work via OpenAlex (cache-first) → snapshots.json.

    Returns {"updated": [...], "no_data": [(slug, why)], "errors": [(slug, why)]}.
    A provider failure records the slug and leaves every existing snapshot
    untouched — no partial snapshot is ever written.
    """
    cache = BibliographicCache(state)
    provider = ADAPTERS["openalex"](
        fetch=live_transport() if live else None,
        cache=cache,
        limiter=RateLimiter() if live else None,
        mailto=mailto,
    )
    jcr = jcr or {}
    snapshots = load_snapshots(state)
    result = {"updated": [], "no_data": [], "errors": []}
    for path in scope_cards(vault, scope):
        slug = path.stem
        fields = read_card_fields(path)
        ref = extract_external_ids(fields.get("source", "") or "")
        if not ref:
            result["no_data"].append((slug, "no DOI/arXiv id in source:"))
            continue
        try:
            record = provider.resolve(ref)
        except ProviderError as err:
            bucket = "errors" if live else "no_data"
            result[bucket].append((slug, err.detail))
            continue
        venue_key = (record.get("venue") or "").lower()
        snapshots[slug] = build_snapshot(
            record,
            work_slug=slug,
            journal_if_text=fields.get("journal_if"),
            jcr_quartiles=jcr.get(venue_key, {}),
        )
        result["updated"].append(slug)
    save_snapshots(state, snapshots)
    return result


def citations_proposal(vault, state, scope="all"):
    """Card-vs-snapshot citation diff as a PROPOSAL report (no card writes)."""
    snapshots = load_snapshots(state)
    lines = [
        "# Citations refresh proposal (generated by palace refresh)",
        "",
        "Card edits require the orchestrator's packaged confirmation.",
        "",
        "| Work | Card citations (dated) | Fetched (dated) | Delta |",
        "|---|---|---|---|",
    ]
    for path in scope_cards(vault, scope):
        slug = path.stem
        fields = read_card_fields(path)
        snapshot = snapshots.get(slug)
        if not snapshot or snapshot.get("citations") is None:
            continue
        card_count = str(fields.get("citations") or "?").split()[0]
        fetched = snapshot["citations"]
        try:
            delta = str(fetched - int(card_count))
        except ValueError:
            delta = "n/a"
        lines.append(
            "| %s | %s (%s) | %s (%s) | %s |"
            % (
                slug,
                card_count,
                fields.get("citations_date") or "?",
                fetched,
                snapshot.get("fetched_at") or "?",
                delta,
            )
        )
    target = Path(state) / IMPACT_DIRNAME / CITATIONS_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def weight_dryrun(vault, state, evaluation_year):
    """Legacy absolute band vs contextual band, per work. Zero Vault writes."""
    snapshots = load_snapshots(state)
    rows = []
    agreements = 0
    covered = 0
    for path in scope_cards(vault, "all"):
        slug = path.stem
        fields = read_card_fields(path)
        legacy = str(fields.get("weight") or "?").split()[0]
        snapshot = snapshots.get(slug)
        if snapshot is None:
            rows.append((slug, legacy, "(no snapshot — run refresh)", "n/a"))
            continue
        verdicts = classify_all(snapshot, evaluation_year)
        summary = "; ".join(
            "%s: %s%s" % (cat, v["band"], "*" if v["coarse_fallback"] else "")
            for cat, v in sorted(verdicts.items())
        )
        bands = {v["band"] for v in verdicts.values()}
        agrees = legacy in bands
        covered += 1
        agreements += agrees
        rows.append((slug, legacy, summary, "yes" if agrees else "NO"))
    lines = [
        "# Legacy-weight dry run (contextual bands, generated by palace refresh)",
        "",
        "Read-only analysis. `*` marks a coarse JCR fallback. Any migration",
        "requires the weight-migration gate with per-batch confirmation.",
        "",
        "Coverage: %d/%d works have snapshots; legacy band matches some"
        % (covered, len(rows)),
        "contextual band on %d/%d covered works." % (agreements, max(covered, 1)),
        "",
        "| Work | Legacy band | Contextual bands (per category) | Agrees |",
        "|---|---|---|---|",
    ] + ["| %s | %s | %s | %s |" % row for row in rows]
    target = Path(state) / IMPACT_DIRNAME / DRYRUN_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target, covered, agreements


def _roots(args):
    if args.vault and args.state:
        return Path(args.vault), Path(args.state)
    from ..tools.config_resolver import resolve_roots

    roots = resolve_roots(args.config)
    return (
        Path(args.vault) if args.vault else roots["vault_dir"],
        Path(args.state) if args.state else roots["state_dir"],
    )


def run(argv):
    parser = argparse.ArgumentParser(prog="refresh", description=__doc__.splitlines()[0])
    parser.add_argument("--kind", choices=("citations", "metadata", "impact"))
    parser.add_argument("--dryrun-weights", action="store_true")
    parser.add_argument("--scope", default="all", help="all | <slug> | domain:<slug>")
    parser.add_argument("--live", action="store_true", help="enable the network transport (gated)")
    parser.add_argument("--jcr-snapshot", help="user-supplied licensed JCR export (JSON)")
    parser.add_argument("--mailto", help="polite-pool contact (default: $PALACE_MAILTO)")
    parser.add_argument("--evaluation-year", type=int, help="default: current UTC year")
    parser.add_argument("--vault")
    parser.add_argument("--state")
    parser.add_argument("--config")
    args = parser.parse_args(argv)
    if not args.kind and not args.dryrun_weights:
        parser.error("nothing to do: pass --kind and/or --dryrun-weights")
    import os

    mailto = args.mailto or os.environ.get("PALACE_MAILTO")
    year = args.evaluation_year or datetime.now(timezone.utc).year
    try:
        vault, state = _roots(args)
        if args.kind:
            jcr = read_jcr_snapshot(args.jcr_snapshot)
            result = refresh_snapshots(
                vault, state, scope=args.scope, live=args.live, jcr=jcr, mailto=mailto
            )
            print(
                "refresh %s: updated=%d no_data=%d errors=%d (live=%s)"
                % (
                    args.kind,
                    len(result["updated"]),
                    len(result["no_data"]),
                    len(result["errors"]),
                    args.live,
                )
            )
            for slug, why in result["no_data"] + result["errors"]:
                print("  - %s: %s" % (slug, why))
            if args.kind == "citations":
                print("proposal: %s" % citations_proposal(vault, state, args.scope))
        if args.dryrun_weights:
            target, covered, agreements = weight_dryrun(vault, state, year)
            print(
                "weight dry-run: %s (covered=%d agreements=%d)"
                % (target, covered, agreements)
            )
        return 0
    except (OSError, ValueError) as err:
        print("refresh error: %s" % err, file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(run(sys.argv[1:]))
